name: Deploy Frontend Exercises to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hyndav/frontend-exercises
      TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f Dockerfile .
          docker push $IMAGE_NAME:$TAG

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes Access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view --minify

      - name: Deploy with Helm
        run: |
          helm upgrade --install frontend-exercises ./helm-deployment \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=$TAG \
            --atomic --cleanup-on-fail
